config/routes.rb
Tweeter::Application.routes.draw do

  resources :posts
  resources :users
  resources :sessions
  resources :followings

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"

  root to: 'posts#index'

end

app/models/following.rb
class Following < ActiveRecord::Base
  belongs_to :follower, class_name: 'User'
  belongs_to :followee, class_name: 'User'
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user

  attr_accessible :body, :user_id

  validates_length_of :body, maximum: 160
end

app/models/topic.rb
class Topic

  attr_accessor :string, :score

  # DISCLAIMER: This would normally be cached / memoized, as it's called on
  # every request to root_path
  def self.all
    topics = []
    @trends = $redis.smembers('trends')
    @trends.each do |t|
      $redis.smembers(t).each do |m|
        if Time.now.to_i - m.split(':').last.to_i > 20.seconds.to_i
          $redis.srem(t, m)
        end
      end
      top = Topic.new
      top.string = t
      top.score = $redis.scard(t)
      if $redis.scard(t) == 0
        $redis.srem('trends', t)
      else
        topics << top
      end
    end
    topics.sort_by{|s| s.score}.reverse
  end

  def self.vote(s)
    $redis.sadd('trends', s)
    $redis.sadd(s, s + ':' << Time.now.to_i.to_s)
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!

  has_many :posts
  has_many :followings
  has_many :followers, through: :followings, class_name: 'User', foreign_key: 'following_id'
  has_many :followees, through: :followings, class_name: 'User', foreign_key: 'followee_id'

  attr_accessible :name, :password, :password_confirmation, :protected

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :name
  validates_uniqueness_of :name

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private
  def not_authenticated
    redirect_to login_path, notice: "Please login first"
  end
end

app/controllers/followings_controller.rb
class FollowingsController < ApplicationController
  before_filter :require_login

  def create
    @following = Following.new(params[:following])
    if @following.save
      redirect_to root_url, success: 'Following created'
    else
      redirect_to root_url, success: 'Error creating following'
    end
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :require_login

  def index
    @posts = Post.order('created_at desc').all.select do |p|
      p.user == current_user or Following.where(follower_id: current_user.id, followee_id: p.user.id).exists?
    end
    @topics = Topic.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(params[:post])
    if @post.save
      @post.body.scan(/\B#(\w+)/i).each do |s|
        Topic.vote(s.first)
      end
      redirect_to root_url
    else
      render :new
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = login(params[:name], params[:password])
    if user
      redirect_back_or_to root_url, success: 'Logged in'
    else
      flash.now.alert = 'Invalid credentials'
      render :new
    end
  end

  def destroy
    logout
    redirect_to root_url, success: 'Logged out'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_login, only: :index

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to root_url, success: 'Signed up!'
    else
      render :new
    end
  end

  def index
    @users = User.all.reject{|u| u.id == current_user.id}
    @followings = {}
    @users.each do |u|
      unless Following.where(follower_id: current_user.id, followee_id: u.id).exists?
        @followings[u.id] = Following.new(follower_id: current_user.id, followee_id: u.id)
      end
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def page(str)
    case str
    when :home
      params[:controller] == 'posts' and params[:action] == 'index'
    when :new_post
      params[:controller] == 'posts' and params[:action] == 'new'
    when :users
      params[:controller] == 'users' and params[:action] == 'index'
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Tweeter
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    .container-fluid
      .navbar.navbar-fixed-top
        .navbar-inner
          .container
            %a.brand{href: root_url} TweeterVU
            %ul.nav
              %li{class: page(:home) ? 'active' : ''}= link_to 'Home', root_path
              %li{class: page(:new_post) ? 'active' : ''}= link_to 'New Tweet', new_post_path
            %ul.nav.pull-right
              - if current_user
                %li
                  %p.navbar-text= 'Signed in as ' << current_user.name
                %li.divider-vertical
                %li= link_to 'Logout', logout_path
              - else
                %li= link_to "Signup", signup_path
                %li.divider-vertical
                %li= link_to "Log in", login_path
      .row-fluid
        .span2
          %ul.nav.nav-list
            %li.nav-header Header
            %li{class: page(:home) ? 'active' : ''}= link_to 'Home', root_path
            %li{class: page(:users) ? 'active' : ''}= link_to 'Users', users_path
        .span10
          - flash.each do |key, value|
            .alert{:class => 'alert-'<< key.to_s}= value
          = yield

app/views/posts/index.html.haml
.row-fluid
  .span7
    %h2 Tweets
    - @posts.each do |p|
      .well
        %span= p.user.name + " says: " << p.body
        %br/
        %span= p.created_at
  .span3
    %h2 Topics
    - @topics.each do |t|
      %p= t.string + " - " << t.score.to_s

app/views/posts/new.html.haml
%h1 New Post

= simple_form_for @post do |f|
  = f.input :body
  = f.input :user_id, as: :hidden, input_html: {value: current_user.id}
  = f.button :submit

app/views/users/index.html.haml
- @users.each do |u|
  .well
    %span= u.name
    - if @followings[u.id]
      = simple_form_for @followings[u.id] do |f|
        = f.input :follower_id, as: :hidden
        = f.input :followee_id, as: :hidden
        = f.button :submit
    - else
      %span You already follow this user

app/views/users/new.html.haml
%h1 Sign up

= simple_form_for @user do |f|
  = f.input :name
  = f.input :password
  = f.input :password_confirmation
  -# = f.input :protected
  = f.button :submit